name: Publish Docker images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        branch: ['master', 'nginx-1.23-php-8.1-sury', 'nginx-1.23-php-7.4', 'nginx-1.18-php-7.4-sury']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sets env vars for Docker image
        run: |
          echo "DOCKER_IMAGE_BRANCH=latest" >> $GITHUB_ENV
        if: ${{ matrix.branch == 'master' }}
      - name: Sets env vars for Docker image
        run: |
          echo "DOCKER_IMAGE_BRANCH=${{ matrix.branch }}" >> $GITHUB_ENV
        if: ${{ matrix.branch != 'master' }}
      - name: Push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ACCOUNT }}/nginx-php:${{ env.DOCKER_IMAGE_BRANCH }}
            ghcr.io/${{ github.repository_owner }}/docker-nginx-php:${{ env.DOCKER_IMAGE_BRANCH }}
